version: '3.8'
services:
  udp_client:
    container_name: motion_detection_udp_client
    restart: always
    build: 
      context: .
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      SERVER_IP: ${SERVER_IP}
      SERVER_PORT: ${SERVER_PORT}
      BUFFER_SIZE: ${BUFFER_SIZE}